[project]
name = "hum-helix"
version = "0.1.0"
description = "hacked stt whisper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "faster-whisper>=1.2.0",
]
